root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/pen2pdf"
  cmd = "go build -o ./tmp/pen2pdf ."
  delay = 1000
  exclude_dir = ["vendor", "tmp", ".git", "bin", "example"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "toml"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
